name: Release Binary

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Build Binary
        run: |
          mkdir -p build
          
          case "${{ runner.os }}" in
            "Linux")
              OUTPUT_NAME="gasp-linux"
              ;;
            "macOS")
              OUTPUT_NAME="gasp-darwin"
              ;;
            "Windows")
              OUTPUT_NAME="gasp-windows.exe"
              ;;
          esac
          
          go build -o "build/$OUTPUT_NAME"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gasp-${{ runner.os }}
          path: src/build/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}